#+TITLE: IVY LIGUE
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="basic.css" />
#+OPTIONS: toc:nil, num:nil

#+BEGIN_EXPORT html
<style>
canvas#canvasvines {
  position: absolute;
  top: 0;
  left: 0;
  display: block;
  margin-left: auto;
  margin-right: auto;
  z-index: -1;
}
</style>
<canvas id="canvasvines"></canvas>
<script type="text/javascript" src="perlin.js"></script>
<script type="text/javascript" src="vines.js"></script>
#+END_EXPORT

#+BEGIN_EXPORT html
<p style="color:#008000">
Pour faire pousser du lierre,<br>
en un clin d'œil,<br>
cliquez,<br>
ici ou là...<br>
</p>
#+END_EXPORT

* Atelier en projet

Entre pratiques « vertes » (semer, planter, végétaliser ou « renaturer
»), expérimentations artistiques et dispositifs universitaires
(questionner et produire des savoirs), cet atelier vise à repenser le
campus de Paris 8 - Vincennes-à-St Denis en tant que « champ » ouvert
à l’expérimentation : lieu où favoriser l’implantation de
(contre)-modèles non arborescents, comme y appelaient Deleuze et
Guattari : herbes, mousses, lierres et lichens, ou toute autre espèce
végétale « compagne ».

Les domaines d’intervention de cet atelier transversal (avec
composante dynamique sur site) se situent au croisement de :

- nouvelles articulations de la recherche en pratiques
  écologiques, écoféministe et écoqueer, à partir d’un corpus
  philo-botanique et de notions telles que celle de plante synanthrope
   la synanthropie désignant la capacité de certaines espèces (flore
  ou faune) à bénéficier d’une association avec un habitat urbain ou
  anthropisé.

- Cet atelier sera également l’occasion d’interroger des
  éléments de langage tels que « renaturation » ou « artificialisation
  » des sols, ainsi que d’inviter des questions reliées aux genres et
  aux récentes convergences de luttes écologiques et éco-queers.

- Un troisième champ d’action implique l’intervention artistique
  à partir de la « boite verte » de Marcel Duchamp, auteur d’une Rain
  Room, d’une pelle à déneiger et d’une feuille de vigne femelle. Ses
  ready-made sont des sources d’inspirations multiples pour un autre
  écosystème, à partir desquels inviter/inventer d’autres projets de «
  récupération », de recyclages, et de branchements
  transdisciplinaires.

- Expérimenter : cet atelier prévoie un déplacement in situ pour
  localiser des possibilités de végétaliser/reverdir un champ «
  culturel » en tant que dispositif susceptible de transformer
  chacun.e en « acteur.rice ».

* Description

Cet atelier transdisciplinaire vise à échafauder des passerelles en
vue de la « réclamation » (reclaim) des communs : un « campus »
constituant une forme de commun (common) lisible à la fois comme champ
de savoir et sol partagé sur lequel faire croître des formes
d’interactions entre vivants « humains » et non-humains.  Un atelier
de 2 heures est prévu, permettant d’articuler la présentation de
recherches contemporaines sur les symbioses et d’opérer une critique
de la notion de « parasitisme », longtemps restée un concept clé pour
penser les relations inter-espèce. Comment transformer un campus en «
boite verte » ?  La plantation de lierre, dont les rameaux fertiles se
propagent au hasard des supports et des hôtes, est une des pistes à
suivre, en lien avec une marche exploratoire sur site, avec repérage
et inventaire des interstices où greffer, machiner, laisser émerger de
façon adventice. Le lierre grimpant permet d’héberger des insectes, de
lutter contrer les effets du réchauffement climatique. Contrairement à
sa réputation de « parasite », il n’endommage pas les supports mais
les protège.  Rampant, il protège les sols.  Recouvrir, revégétaliser
(à moindre coût) les interstices d’un campus, permettrait d’y inviter
une expérimentation trans-espèce, ouverte aux métamorphoses  , d’y
aménager des espaces potentiels, des fonds d’œuvre (comme la verdure
d’Etant donnés) et d’y respirer un air dépollué, libéré de son ampoule
(Duchamp, « Air de Paris » (1919).

Lorsque Duchamp quitte Paris pour New York en 1919, il emporte avec
lui un ready-made portable, une ampoule pharmaceutique vidée de son
contenu et resoudée. Duchamp se définie alors comme « respirateur
». La respiration et la circulation sont au cœur des préoccupations
duchampiennes.

Parmi les plantations proposées de nombreuses plantes peuvent être
mentionnées, outre le lierre grimpant, reconnu pour son absence
d’impact négatif sur les supports, et qui fleurit à la rentrée du
calendrier universitaire : de septembre à octobre. Cet atelier sera
l’occasion d’évoquer d’autres espèces « compagnes », pour reprendre la
formule de Donna Haraway : « nous ne sommes pas autonomes, notre
existence dépend de notre capacité à vivre ensemble ».  (When Species
Meet, p. 4) ; et de resituer le questionnement végétal et les
questions climatiques dans le contexte des études de genre auxquelles
se rattachent les trois porteur.e.s du projet, sur fond de « politique
régénérative des corps » (O. Potot, « Nous sommes tout.e.s du lichen,
Chimères n°82, 2014/1).

* Organisatrices

** Alexandra PICHETA
- Email : [[mailto:alpicheta@gmail.com]]
- Université de Paris 8 /NYC, New School for Social Research

** Eugénie PERON-DOUTE

- Email : [[mailto:eugenie.perondoute@yahoo.fr]]
- Université de Limoges /Université de Guelph (Canada)

** Marie Dominique GARNIER

- Email :  [[mailto:marie-dominique.garnier@univ-paris8.fr]]
- Université de Paris 8 St Denis
* Local Variables :noexport:
Local Variables:
org-html-postamble: "Procedural vines by Gabriel Giamarchi, using perlin noise from Stefan Gustavson."
End:
